### ISSUE TITLE
Prácticas 

### ISSUE THREAD

**Issue by Anais-droid** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Anais-droid#2]
[matematematicas discretas, Anais M.M..pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-Anais-droid/files/12591100/matematematicas.discretas.Anais.M.M.pdf)

**Comment by DiegoLV117** [comment]
Portada 25%
Procedimiento 20%
Figuras,ilustraciones y fotografias 25%
Resultados y Clnclusiones 12% (No tiene conclusion)
 Calificacion 16/20                  
Calificado por el equipo de Elisa Sanchez Coronel

**Comment by josealfredo79** [comment]
Bien hecho
